version: '3'
services:
  platform_test:
    image: platform_test
    ports:
      - "8080:8080"
    depends_on:
      - localhost
    volumes:
      - ./:/go/src/github.com/mrsmuneton/platform-test

  localhost:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
