version: '3.8'

networks:
  shared-network:
    driver: bridge

services:
  
  db:
    container_name: db
    networks:
      - shared-network
    image: postgres:13-alpine
    ports:
      - 5432:5432

  api:
    container_name: api
    networks:
      - shared-network
    image: api-amd64:1.0
    ports:
      - 8080:8080 # CRUD API
    depends_on:
      - db